services:
  guitar_database:
    image: postgres:alpine
    container_name: flower-shop-backend
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitars